### ISSUE TITLE
Maybe a Bug in the Proxy

### ISSUE THREAD

**Issue by lmxyy** [Hzfengsy/CS391-Assignment#1]
<img width="836" alt="default" src="https://user-images.githubusercontent.com/10475754/46277648-56649a00-c596-11e8-90e5-4b1687b11922.png">
Do you need to replace the `outputdata` with `buffer`?

**Comment by Hzfengsy** [comment]
That is obviously a bug. In fact, I have not fully completed proxy project. Next time I'll create a _dev_ branch to upload unfinished code.
